<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function middleware($middleware, array $options = [])
    {
        return parent::middleware($middleware, $options); // TODO: Change the autogenerated stub
    }

    protected function dispatch($job)
    {
    }
    public static function __callStatic($name, $arguments)
{
    // TODO: Implement __callStatic() method.
}



}
